### ISSUE TITLE
Fresnel - making API more consistent with existing code?

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#103]
attn @douglase @kuravih 

I'm trying to work through some more of the details of this, in part while sorting out how to handle image planes better. Here is a minor API detail, which led me to think about some larger goals. 

Right now the distance between optics seems to need to be in 2 different places. In the Hubble example: 

```
# Propagate to secondary
gw.propagate_fresnel(d_pri_sec, display_intermed=False)

#apply secondary
gw.apply_optic(g2,d_pri_sec)
```

The `d_pri_sec` term shows up in both. Why? In `propagate_fresnel`, that makes sense, that's how far to propagate. In `apply_optic`, it's used to calculate the beam radius at that position. But couldn't it also get that information from the `.z` attribute of the wavefront object? 

I guess right now I don't totally understand the mix of what's happening in `apply_optic` versus the propagation. In the original Fraunhofer regime code, there is a clear line between propagation and interaction with optics, such that a given optic can be applied to a wavefront without need for considering the details of what came before. The wavefront object alone contains all the info the optic needed to access.  It seems like that should also be feasible here, that we can keep enough state with the `fresnel.Wavefront` such that it can be accessed by any optics.  Or am I missing something? 

Here is some hand-wavy mock code we could work towards? 

```
FS = FresnelOpticalSystem(diam=2.4)
FS.addOptic(hubble_primary)
FS.addOptic(hubble_secondary, distance=d_pri_sec)
FS.addDetector(pixelscale=whatever, distance=d_sec_to_focus)
fresnelPSF = FS.calcPSF(args)
```
Then inside the Fresnel version of calcPSF, instead of the current code that does

```
        for optic in self.planes:
            wavefront.propagateTo(optic)
            wavefront *= optic
            current_plane_index += 1
```
instead we would have something like:
```
        for optic, distance in zip(self.planes, self.distances):
            wavefront.propagate(distance)
            wavefront *= optic
            current_plane_index += 1
```

Does that make sense? I'm trying to think whether we can make the Fresnel code have as user-friendly an interface as possible modeled on the Fraunhofer code.

**Comment by douglase** [comment]
I think this makes sense, the other scenario I can think of would be someone wanting to just do Gaussian laser beam optics to find the waist at each optic, and they might not care to take the processing time to propagate the wavefront through. 
But in that case this same loop could work, except we add an ignore_wavefront flag as there is in  apply_optic() to the propagate_fresnel().

**Comment by mperrin** [comment]
At this point I have the FresnelOpticalSystem infrastructure pretty much working in my local repository, with an API close to the mock code above (but not exactly).

Still TBD is carefully sorting through the issue #104 stuff, and getting the image plane coordinates conversion working. For the latter I think I'm going to add some infrastructure to `Wavefront` to track focal length and f ratio of the beam, which will enable automatic support for pupil coordinates in angular units as well as meters.

**Comment by mperrin** [comment]
I have just pushed a very substantial set of changes to the Fresnel branch. These implement the `FresnelOpticalSystem`, including support for image planes.  As part of this there has also been some refactoring of the API to bring it more consistent with the rest of `poppy`.   **This probably breaks essentially all existing code using the Fresnel parts** - apologies for that, but better sooner than later to restructure the API.  After the change it's all very closely consistent to the regular `OpticalSystem` API.

Specifically:
 - renaming of fresnel.Wavefront to `FresnelWavefront`, various propagation routines to e.g. `_propagate_wts` and so forth
 - `apply_optic` is now `apply_lens_power` and the call signature changed. There is no need to pass in a distance `z` since the `FresnelWavefront` keeps track of its own location.
 - in any case you don't need to call `apply_optic` manually since it can now be applied just by multiplying by the object, like any other `OpticalElement`
 - `FresnelOpticalSystem` provides a high level container for a series of elements, with a consistent API and outputs as regular `OpticalSystem`

There is now a new notebook in the Notebooks directory that demonstrates all of this. See https://github.com/mperrin/poppy/blob/fresnel/notebooks/Fresnel_Propagation_Demo.ipynb
There's also a bunch of new unit tests including the Hubble example worked pretty thoroughly.

Some caveats:
 - `Detector` classes not yet supported in `FresnelOpticalSystem`; you can get PSFs out just fine, but on the pixel sampling defined by the FFT. This is probably the next thing to add. 
 - the `force_fresnel` parameter was removed, since now `FresnelWavefront` does always propagate via Fresnel and does *not* attempt to fall back to Fraunhofer. Mixed propagation like that wasn't workable in practice with the revised infrastructure, and in any case the support for image planes in the regular Fresnel propagation is a better way of handling them than switching propagation types midstream. That was just too confusing. (and I can't think of a compelling use case for this)
 - The new API is pretty clean; general users can just use `poppy.FresnelOpticalSystem` and add elements to that, and everything is handled automatically in terms of getting a `FresnelWavefront` instead of regular `Wavefront`, and converting plane types and so forth. But the price to pay for cleaner code in the future is having to change a bunch of stuff now. Apologies again.
 - There's almost certainly still some rough edges in places. Let me know what breaks. And suggestions for further tweaks are much welcomed. 


I'm away on vacation next week but will be checking email at least one a day. I wanted to push what I've managed to get done sooner rather than later. Let me know what you think...

**Comment by josePhoenix** [comment]
Nice notebook! Should we open a PR from mperrin/poppy@fresnel? Then we can comment on the code as well.

**Comment by mperrin** [comment]
Fresnel PR has been merged to master.
