### ISSUE TITLE
Fresnel - possible off-by-one bug in fft_coords()?

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#104]
I am not totally sure about this one... Here is a slight difference in behavior between the `Wavefront.coordinates` function and `fresnel.Wavefront.fft_coords`. I am not sure if this is intentional or accidental? 

Compare:
```
In [9]: wf = fresnel.Wavefront(2.4*u.m, wavelength=675e-9, npix=512, oversample=2)
In [10]: wf.fft_coords()[1][0]
Out[10]: array([-4.8     , -4.790625, -4.78125 , ...,  4.771875,  4.78125 , 4.790625])
```
versus: 
```
In [11]: wf.coordinates()[1][0]
Out[11]: array([-4.7953125, -4.7859375, -4.7765625, ...,  4.7765625,  4.7859375, 4.7953125])
```

In the latter case, I took care to make sure that the output coordinates are centered on the optical axis; i.e. the positive and negative values are symmetric. This is not the case for what fft_coords returns. 
The difference in code is just 1:
```
        x -= (shape[1] - 1) / 2.0   # in Wavefront.coordinates
        x-= (self.shape[1])/2.      # in fresnel.Wavefront.fft_coords
```

I tried changing `fft_coords` to match the behavior of `coordinates`. After doing do, the propagation still seems to work. However the `test_CircularAperturePropagation()` then fails, because the peak value is not as expected. Where did the expected value "3.3633280006866424" come from?  

I am worried that it is inconsistent as currently coded, that as a result the center (x,y)=(0,0) for e.g. a CircularAperture is not the same as the center used in calculating the radial phase term in a plane-to-plane propagation.

**Comment by mperrin** [comment]
Digging into this a bit more, with the current `fresnel` code (without the -1), the output wavefront in the CircularAperturePropagation test case is symmetric around the intersection between 4 pixels at the middle of the array, coordinates (1023.5, 1023.5).  All 4 of those pixels have the same value.   

On the other hand, with the -1 included to be similar to Wavefront.Coordinates, then the output wavefront from the test case is not symmetric. One of the pixels is brighter than the others.

So that seems to confirm the code is correct as-is. This only gets used in the PTP and Direct propagations. Having thought about the spatial frequencies as output by the FFT it makes sense to me that this is the case. 

Moral of the story? The code is correct, but the comment that `ft_coords` "Replaces poppy.wavefront.coordinates()" is not. We are going to have to keep these as separate functions.

Thoughts?

**Comment by douglase** [comment]
Yep, you got to the bottom of it. The docstring comes from the fact that I originally used Wavefront.Coordinates() and only in testing discovered the difference and "replaced" it with the custom function.

The test value should probably be rounded, it's just the value I was getting at the time I wrote the test, and only within +-0.1 of the value in the cited Anderson and Enmark figure.
