### ISSUE TITLE
ZernikeWFE doesn't set pupil_diam correctly

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#119]
I think I haven't fully grokked where POPPY uses `pupil_diam`, but having it missing leads to being unable to sample the ZernikeWFE optic at some fixed npix across the circular aperture. The easy fix is to just set `self.pupil_diam = 2 * self.radius`, but I can see places where common code can be factored out of ZernikeWFE and ParameterizedWFE.

**Comment by josePhoenix** [comment]
By "unable" I just mean extra padding is added... so you'd have to work backwards to get just the central pixels.

**Comment by josePhoenix** [comment]
Okay, maybe the solution is really to pass `grid_size` through to `sample` from `display`.

**Comment by mperrin** [comment]
The main place in which `pupil_diam` is used is in `OpticalSystem.inputWavefront()`, in which the `pupil_diam` of the first optical plane is used to define how big the input wavefront ought to be. 
Then you found the other place it's used, in `AnalyticWavefront.sample()` (and by extension in `.display()`). 

Now I can't remember where the `grid_size` parameter came from. Was that you or me? I agree that it should be passed through to sample from display. `grid_size` is sort of an awkward and non-obvious parameter name, but I'm not sure e.g. `sampling_array_diameter` would be any better.

**Comment by mperrin** [comment]
is this issue something we should fix before the 0.4 release?

**Comment by josePhoenix** [comment]
I'm not sure if it's an issue, actually. I think I decided to pass grid_size through instead.

**Comment by josePhoenix** [comment]
See https://github.com/mperrin/poppy/commit/f3f9a574b45a05e5789fb334fc6697ce31ac6427#diff-dc09de967bc8916dce19b8127675ee73R143

I don't think there's any need to set `pupil_diam` any more?

**Comment by mperrin** [comment]
aaaargh I entered the wrong issue number in the commit message *again*. second time today. blargh. The above commit actually addresses #111, *not* #119.
