### ISSUE TITLE
better document the zernikeWFE class in poppy docs

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#142]
@douglase tells me he couldn't find anything about the zernike optics class in the docs, and indeed it seems like the ZernikeWFE class is only mentioned in the release notes but not actually documented anywhere. 

@josePhoenix could you put together a couple paragraphs about this, and/or some notebook code?

**Comment by josePhoenix** [comment]
For anyone searching for this, there is an example notebook already: https://github.com/mperrin/poppy/blob/master/notebooks/ThinLens_ZernikeWFE_and_ParameterizedWFE.ipynb

I'll write a more complete document for the online HTML docs.

**Comment by mperrin** [comment]
Hi @josePhoenix can you give me an estimate for when you might be able to work on this? This and #144 are the only remaining issues for the next release.

**Comment by josePhoenix** [comment]
Working on it right now, but got sidetracked by some refactoring in `wfe.py`

**Comment by josePhoenix** [comment]
One thing is that I think I'll need to expose ZernikeWFE and friends under the main poppy namespace to get the `automodapi` helper to find them. This won't break any existing code.

**Comment by mperrin** [comment]
Yes go for it. Exposing them in the main namespace also helps make them more apparent to users so it's win-win.

**Comment by josePhoenix** [comment]
It appears that `hexike_basis` no longer works as described in the demo notebooks (or at all), so I'm investigating that as part of this issue
