### ISSUE TITLE
Add MatrixFTCoronagraph to docs and release notes

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#144]
@neilzim let's remember this for the release

**Comment by neilzim** [comment]
Right, just to clarify - inside docs/ we want a statement at the top of relnotes.rst under 0.4.1, and a new .rst for the MatrixFTCoronagraph subclass?

**Comment by mperrin** [comment]
Sure that would work. Looking at this now I see the SemiAnalyticCoronagraph docs (which are very brief) are a mention of its existence in classes.rst and then an example in examples.rst. So you could also do that. But I do like the idea of a new page. Maybe we make a 'coronagraphs.rst' and we can put there some discussion of both the SemiAnalyticCoronagraph and the MatrixFTCoronagraph?

**Comment by neilzim** [comment]
Yeah that sounds good.

**Comment by mperrin** [comment]
Hi @neilzim can you give me an estimate for when you might be able to work on this? This and #142 are the only remaining issues for the next release.

**Comment by neilzim** [comment]
@mperrin I will finish this by the end of Thursday.

**Comment by neilzim** [comment]
Ok, I'm satisfied with my draft for the new coronagraphs.rst. I added it to the list under the Contents of index.rst. However, Travis CI is failing on the following warning:
checking consistency... /home/travis/build/neilzim/poppy/docs/coronagraphs.rst:: WARNING: document isn't included in any toctree
Any idea on how to fix this?

**Comment by josePhoenix** [comment]
Look in index.rst for the toctree block and add a line for coronagraphs, I believe

**Comment by neilzim** [comment]
The build with the new docs is fixed.
