### ISSUE TITLE
Fix failing Travis build

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#146]
The travis build is currently broken (https://travis-ci.org/mperrin/poppy/branches)

It's back to the inscrutable python failure ("The command "python setup.py $SETUP_CMD" exited with 247.") which we know from past experience actually means "your test has tried to use too much RAM or taken too long and has timed out".  

The matrixFT coronagraphic propagation test has to be the guilty party. I just ran it here and it looks like it got up to about 12 GB.  

We will need to either figure out how to make Travis happier with large RAM allocations or develop a slimmed down test case. 

attn @neilzim @josePhoenix

**Comment by mperrin** [comment]
Travis docs say the test VMs have 3 GB RAM. See on https://travis-ci.com/plans

**Comment by neilzim** [comment]
I'll try to scale down the calculation.
