### ISSUE TITLE
Update link to pysynphot RTD doc

### ISSUE THREAD

**Issue by pllim** [mperrin/poppy#161]
Please change http://ssb.stsci.edu/pysynphot/docs/ to http://pysynphot.readthedocs.org/en/latest/ . The old link will still redirect, but it is probably cleaner to just point to the new link. Thanks!

**Comment by mperrin** [comment]
Yes - I'd actually changed this already in my local copy after your earlier email, but hadn't pushed the changes yet to here.

**Comment by mperrin** [comment]
changed in commit https://github.com/mperrin/poppy/commit/70a9b3e7965467a16c8ae1350275e69d57b6ab1c

I'll build a new copy of our HTML docs and push them online later also.

**Comment by pllim** [comment]
Looks good. Thanks!
