### ISSUE TITLE
poppy docs need to be updated

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#19]
These are issues with the `poppy` docs that should be fixed prior to our next release. @mperrin: please add any others as they occur to you. 

  - [x] Sphinx docs for classes.rst not making links for all classes. #17 
  - [x] add documentation for saving analytic pupils to a FITS file #9 
  - [x] add a label for the poppy homepage so we can intersphinx link to it
  - [x] replace http://www.stsci.edu/~mperrin/software/poppy with a redirect to the pythonhosted.org docs
  - [x] missing about or about_team label
```
/Users/jlong/dev/poppy/docs/index.rst:60: WARNING: undefined label: about_team (if the link has no caption the label must precede a section header)
/Users/jlong/dev/poppy/docs/relnotes.rst:8: WARNING: undefined label: about_team (if the link has no caption the label must precede a section header)
/Users/jlong/dev/poppy/docs/relnotes.rst:82: WARNING: undefined label: about (if the link has no caption the label must precede a section header)
```
  - [x] undefined reference `opticalelement` (from docstring?)
```
/Users/jlong/dev/poppy/docs/api/poppy.OpticalSystem.rst:45: WARNING: undefined label: opticalelement (if the link has no caption the label must precede a section header)
```
  - [x] Improve documentation for `poppy.Instrument` class and how to write your own instrument subclass.  Document common Instrument functionality (in POPPY docs)
  - [x] Add documentation for package level configuration settings to POPPY
  - [x] Explain `use_multiprocessing`
  - [x] Installation docs should be updated like WebbPSF's were (pysynphot install)

**Comment by mperrin** [comment]
web redirects added for http://www.stsci.edu/~mperrin/software/poppy
