### ISSUE TITLE
Adding detector to Fresnel Optical Systems

### ISSUE THREAD

**Issue by maciekgroch** [mperrin/poppy#190]
I encountered a problem with adding Fresnel detector, explicitly the following method (line 1002 in fresnel.py):

```
@u.quantity_input(distance=u.m)
 def add_detector(self, pixelscale, distance=0.0 * u.m, **kwargs):
        super(self, FresnelOpticalSystem).addDetector(pixelscale, **kwargs)
        self.distances.append(distance)
        if self.verbose:
            _log.info("Added detector: {0} after separation: {1:.2e} ".format(self.planes[-1].name, distance))
```

shouldn't it be:
`super(FresnelOpticalSystem, self).addDetector(pixelscale, **kwargs)`
I simply reversed the order of the arguments. After all, I believe the code was developed for Python3.+, therefore, cannot you write:
`super().addDetector(pixelscale, **kwargs)`

**Comment by josePhoenix** [comment]
Yeah, you're right. Looks like that's not exercised by the test suite at all. If you have the time, could you open a pull request with your fix?

**Comment by maciekgroch** [comment]
I was away for the weekend. I will do that later today.

30 wrz 2016 17:09 "Joseph Long" <notifications@github.com> napisał(a):

**Comment by maciekgroch** [comment]
I think we can close the issue.
