### ISSUE TITLE
poppy.utils.display_PSF behaves oddly when called more than once

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#21]
I expected that display_PSF would either replace the currently shown PSF with another, or create a new figure and display it there. Instead, it adds a second color bar and replaces the PSF. Should be easy enough to create a new figure instead.

![screen shot 2014-12-09 at 3 45 52 pm](https://cloud.githubusercontent.com/assets/172886/5365511/c44b1042-7fba-11e4-9947-8d0c8ccb22ba.png)

**Comment by mperrin** [comment]
Low return on investment, complicated interation with matplotlib state machine. Should be dealt with eventually but not critical for 0.3

**Comment by josePhoenix** [comment]
Okay, I've been investigating this. Using the PyPlot API allows us to maintain the illusion that one can draw an image and colorbar given a single set of axes. This is not the case!

Under the hood, colorbar creates a new axes object, which is why clearing the current axes is not enough. Fortunately, a `matplotlib.image.AxesImage` retains a reference to the last colorbar created for it, so we can reach in and grab a reference to that colorbar, which gets us a reference to the axes the `colorbar()` wrapper created behind the scenes, and we can pass that in to `colorbar()` again as the `cax=` argument.

:cactus:

**Comment by josePhoenix** [comment]
Of course, if the *orientation* of the colorbar changes between two calls, that won't help. The correct way to do things would be to remove the colorbar entirely, but apparently the creation of horizontal colorbar axes adjusts the right padding of the image in a way that it won't automatically go back where it was.

http://stackoverflow.com/questions/5263034/remove-colorbar-from-figure-in-matplotlib

**Comment by josePhoenix** [comment]
There's nothing in the POPPY code that uses the colorbar orientation option, though. I'm in favor of making the `display_PSF` function less flexible, but idempotent, by eliminating that option and adding the workaround described above.

**Comment by mperrin** [comment]
Well, personally I find the orientation keyword to be useful (which is why I added it originally!). Sometimes  one is stacking multiple plots horizontally and wants color bars below each figure, sometimes one is stacking plots vertically and the color bars should be to the side. 

If you just add the workaround but do not remove the orientation keyword, does that yield idempotent behavior in the case where the orientation of the colorbar does not change between the calls?  If so, we could avoid changing the current API and still get improved behavior over the current case, for probably >90% of the use cases where the color bar orientation isn't supposed to change.

**Comment by josePhoenix** [comment]
Yes, using the workaround and relying on users not to try and change colorbar orientations without creating a new figure first would fix this issue. It would also create a new issue where trying to switch orientations would make a really weird looking plot, effectively pushing the bugged behavior into a new (smaller) set of use cases.

It's just unsatisfying to me to have a function that can't do everything it appears to from a cursory inspection of the arguments... and can't even warn you when you're using it wrong!

(I'm sure we're reaching the point of diminishing returns on investing time in this issue, but I just can't resist.)

**Comment by josePhoenix** [comment]
Closed by PR #82
