### ISSUE TITLE
Wavefront display option

### ISSUE THREAD

**Issue by maciekgroch** [mperrin/poppy#210]
I found a really small issue (however pretty anoying...): 
In `popp_core display()`  
```
if what == 'intensity':
                # ...
elif what == 'phase':
                #...
elif what == 'both':
                # ...
else:
            raise ValueError("Invalid value for what to display; must be 'amplitude', 'phase', or 'both'.")
```
The error message is incorrect -- you cannot display 'amplitude', only 'intensity'. Nevertheless it would be nice to plot just amplitude.

**Comment by mperrin** [comment]
Sure, that seems reasonable. We may not have time to get around to this for a while, but if you feel like making a pull request with the fix we'd be glad to merge that in. Thanks.
