### ISSUE TITLE
Reference to poppy.py in fft_optimization.rst

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#22]
```
Set `__timetests__=True` in `poppy.py` to enable some rudimentary benchmarking for the FFT section of the code.
```

For later investigation. May be out of date.

**Comment by mperrin** [comment]
fft_optimization.rst is actually in webbpsf/docs, not poppy/docs.  Should we move it to poppy/docs?

**Comment by mperrin** [comment]
I updated the doc text, but we should probably relocate this to the poppy docs, and just link to it from the webbpsf docs. I'll leave that for another day as I need to pack for my trip tomorrow...

**Comment by josePhoenix** [comment]
Great! I'll open a new issue for relocating it, then.
