### ISSUE TITLE
Add option for CompoundAnalyticOptic to add transmissions

### ISSUE THREAD

**Issue by corcoted** [mperrin/poppy#226]
Currently CompoundAnalyticOptic calculates the transmission as the product of the transmissions of the constituent elements.  I'd like the possibility of _summing_ the transmissions to make it easier to generate compound apertures.

For example
```python
poppy.CompoundAnalyticOptic(opticslist=[poppy.RectangleAperture(width=1*u.m, height=0.5*u.m),
    poppy.RectangleAperture(width=0.5*u.m, height=1*u.m)])
```
results in a square aperture, but I would like a cross-shaped one.

A work-around is to invert the apertures, combine them, then invert again, but I'd like something more direct.

**Comment by mperrin** [comment]
This feature was implemented in PR #227, but we forgot to close the issue at the same time.
