### ISSUE TITLE
Incompatibility with Quantity changes in astropy dev 

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#228]
Submitted via email by @tepickering: 

>i’m using poppy in my wfs code to generate pretty PSF images.  i’ve noticed in the past week or two that my integration tests against astropy-dev have started breaking.  in each case, it looks like some Quantity related issue somewhere deep in poppy.  here’s an example:
>https://travis-ci.org/MMTObservatory/mmtwfs/jobs/248992283
>no biggie on my end, but with astropy 2.0 not too far off on the horizon, i figured i’d give you a heads-up…

**Comment by mperrin** [comment]
Fixed in master, by 003f08b and a few subsequent commits

**Comment by tepickering** [comment]
thanks! cloned from github and it's working for me now locally...
