### ISSUE TITLE
display_psf markcentroid overrides imagecrop but shouldn't

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#231]
Setting the `markcentroid` option makes the `imagecrop` option get ignored. These two plots ought to have the same area but don't. 

Note, the screen shot shows a call to `webbpsf.display_psf` but that's really just `poppy.display_psf` by another name. 

![screen shot 2017-08-09 at 11 16 38 am](https://user-images.githubusercontent.com/1151745/29129300-52235a8a-7cf4-11e7-9b28-7807f06446a1.png)

**Comment by mperrin** [comment]
@robelgeda, here is a small and hopefully simple-to-fix bug we just noticed. @josePhoenix thought this might be a good quick task for you as you start to dive into this codebase.

**Comment by robelgeda** [comment]
@mperrin I just noticed this. Look into it now.
