### ISSUE TITLE
Migration to ReadTheDocs

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#232]
It appears that https://pythonhosted.org/ quietly removed the ability to upload new ZIPs of documentation. 😿 

ReadTheDocs.org is more featureful (in some ways), and more commonly used. The reason we weren't using it already is that (when we last checked) projects that depend on SciPy and NumPy wouldn't build correctly in their environment. This appears to be fixed now.

## Migration Checklist

  - [x] Create project at readthedocs.org
  - [x] Add @mperrin as maintainer on ReadTheDocs
  - [x] In Advanced Settings, check "Install your project inside a virtualenv using setup.py install"
  - [x] Fill in `docs/conf.py` as "Python configuration file"
  - [x] Fill in `docs/rtd-pip-requirements` as the "requirements file"
  - [x] Check "Give the virtual environment access to the global site-packages dir." (This makes SciPy and friends available.)
  - [x] Select CPython 3.x as the interpreter
  - [x] Configure / verify the [GitHub webhook](http://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation)
  - [x] Update project homepage on PyPI / in `setup.py`
  - [x] Search for any references to pythonhosted.org in the source

Built docs are at http://poppy-optics.readthedocs.io/en/latest/ for `master` and http://poppy-optics.readthedocs.io/en/stable/ for `v0.6.0`. (Unclear whether RTD sorted the tags and picks "stable" on its own...)

**Comment by mperrin** [comment]
Absolutely superb. I did not expect you to get this done so fast! I'll grant that deadlines are a good motivator, though!

I've just made a small tweak to the RTD config so the default docs shown at http://poppy-optics.readthedocs.io/ are the stable version rather than the latest.

**Comment by mperrin** [comment]
This is all working well now, except for the eventual deprecation and removal of the old docs on pythonhosted, which we're leaving in place for now intentionally.
