### ISSUE TITLE
Phase and ampliude modulation

### ISSUE THREAD

**Issue by FredericCassaing** [mperrin/poppy#264]
Hi Poppy, 
I am completely new to poppy (&github btw) but I have choosen to use it for my research rather than my custom IDL tools.
However, there are a few things I have not seen reading the documentation. Is it possible with the current poppy, or expected with next versions, to perform :
- phase modulation : define a "diversity", as a list of successive phases (screens, or DM/zernike coefficients), so that their application leads to a list of successive PSFs (ie of dimension 3)?
- amplitude modulation/disturbance: I have mainly seen fonctions (in hexdm for example) to alter the phase, is the same easily possible with amplitude ? Unfortunately, complex phase is not supported. 
Thanks in advance for your answers, and
best regards from a new popper !

**Comment by mperrin** [comment]
Hi Frederic, I’ll be happy to help with this. But first, we have moved primary development of poppy over to the repo at github.com/spacetelescope/poppy. Could you please repost this question there? That will let the rest of the dev team besides me to also see the discussion. Cheers.

**Comment by FredericCassaing** [comment]
Hi Marshall,
Thank you for your fast answer, I sent the question to the other repo.
Please just tell me if there is anything more I have to do here to close the issue.
Cheers,
