### ISSUE TITLE
"adjustable" is misspelled in the matrixDFT API

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#37]
Lest this be preserved for posterity like the [HTTP Referer](https://en.wikipedia.org/wiki/HTTP_referer#Origin_of_the_term_referer) (sic) header, we should fix the spelling where it appears. If necessary, backwards compatibility aliases can be added that emit a deprecation warning.

**Comment by mperrin** [comment]
Oh good grief.  And good catch on this one!  Not sure if it was me or Anand who goofed to begin with but I'm totally willing to take the blame.  

Yes by all means let's just fix it flat out, and not worry about back compatibility aliases. Anyone who's actually calling this argument explicitly ought to just update their code.

**Comment by mperrin** [comment]
In terms of clarity of API, would this actually be better named 'CENTERED', since that's really the intent of its behavior? Although I suppose the `offset` parameter means you can get non-centered PSFs so maybe we leave it as is.

**Comment by josePhoenix** [comment]
I dunno, `centering="CENTERED"` reads a bit weird to me. Of course, if we're renaming it anyway, might as well give it the best name! Your call.

**Comment by mperrin** [comment]
Fair enough. Let's leave it as is. (well, spelled correctly now.)

**Comment by josePhoenix** [comment]
Sounds good!
