### ISSUE TITLE
Move fft_optimization.rst from WebbPSF to POPPY docs

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#50]
It's more of a POPPY thing than a WebbPSF thing, and now we can easily link to POPPY docs from the WebbPSF docs, so might as well move it.

**Comment by mperrin** [comment]
This is easy to move if we just copy and add the file; sort of a pain if we care about propagating the git history from the old file in webbpsf to the poppy repository. I can't think of any reason that makes that compelling, so I think I am just going to copy, add to poppy, and delete from webbpsf.

**Comment by mperrin** [comment]
All done now, yes?

**Comment by josePhoenix** [comment]
Will be once we release and upload new docs.
