### ISSUE TITLE
The multiprocessing pool should cap the number of processes at the number of wavelengths required

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#54]
While messing with multiprocessing, I realized POPPY was spawning 4 processes for my 2 wavelength calculation. We should cap the size of the pool at nlambda. (Of course, that's not a common nlambda value, but the point stands.)

**Comment by mperrin** [comment]
I'm confused by this one; it looks like there is already code to limit the number of processes to no more than the number of wavelengths. 

https://github.com/mperrin/poppy/blob/master/poppy/utils.py#L1233-1234

**Comment by josePhoenix** [comment]
Yeah, I saw that code after I made the issue... I'll need to see if I can
make a test case.

**Comment by mperrin** [comment]
Now that multiprocessing is reliable (on 3.4 anyway) it would be nice to either figure out how to reproduce this problem, or else close this issue?

**Comment by mperrin** [comment]
Is there any need to keep this issue open?

**Comment by mperrin** [comment]
Unless I hear any objection by Friday this week I am going to mark this one closed.

**Comment by mperrin** [comment]
Aha, no, I think the issue was the estimate_optimal_nprocesses was working properly but if the user sets `conf.n_processes` explicitly then it overrides, even if the `conf.n_processes` is more than `nwavelengths`. Easy one-line fix.

**Comment by mperrin** [comment]
Fixed in fa1a23a but I accidentally put the wrong issue number in that commit message. Too many browser tabs open!
