### ISSUE TITLE
Display of compound analytic optics problem

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#6]
The following does not seem to display the phase of the defined compound lens correctly:
```
poppy.CompoundAnalyticOptic( [
        poppy.CircularAperture(), 
        poppy.ThinLens(nwaves=2, reference_wavelength=2e-6)]
                            ).display(what='both')
```

![screen shot 2014-08-14 at 6 47 51 pm](https://cloud.githubusercontent.com/assets/1151745/3928126/0c3d4b48-2405-11e4-91a0-947383ebe235.png)

Display of the optics individually works fine. 

```nwaves=4
wavelen=2e-6
osys = poppy.OpticalSystem("test", oversample=2)
osys.addPupil( poppy.CircularAperture(radius=3))    # pupil radius in meters
osys.addPupil( poppy.ThinLens(nwaves=nwaves, reference_wavelength=wavelen))
osys.addDetector(pixelscale=0.01, fov_arcsec=4.0)
osys.display(what='both')
```

![unknown](https://cloud.githubusercontent.com/assets/1151745/3928142/4603e576-2405-11e4-99f6-1f1bd60e3cd6.png)

**Comment by josePhoenix** [comment]
Checked, works.
