### ISSUE TITLE
cleanup wfe.py; rationalize with ZernikeAberration class and related. 

### ISSUE THREAD

**Issue by mperrin** [mperrin/poppy#67]
@josePhoenix  - The existing wfe.py file is mostly a placeholder left over from early steps towards adding Zernike aberrations and other WFE forms. The partial Zernike WFE class in there is now almost certainly obsolete and redundant with your ZernikeAberration class, so we should take it out so there is one and only one obvious way to implement Zernike-based WFE. 

The other classes are just notional hand wave placeholders; I'd probably comment them all out entirely although I wouldn't just delete them outright since I think in the long run we will want some other forms of aberrations besides just Zernikes.

**Comment by mperrin** [comment]
I think this would also be good to do (at least partially) for this release. Mostly just to avoid having 2 incompatible Zernike classes present.

**Comment by josePhoenix** [comment]
We should delete them outright :) Version control means you can delete things with no consequences.

I propose moving ZernikeAberration into wfe.py and removing the rest. It makes sense as a logical grouping, we just only have one thing to put in it for now.
