### ISSUE TITLE
Python 3 incompatibility in poppy_core.py

### ISSUE THREAD

**Issue by marioavellaneda** [mperrin/poppy#70]
Two lines in the poppy_core.py file are Python3 incompatible (lines 2145-2150):

            if len (self.opd.shape) != 2 or self.opd.shape[0] != self.opd.shape[1]:
                _log.debug('OPD shape: '+str(self.opd.shape))
                raise ValueError, "OPD image must be 2-D and square"

            if len (self.amplitude.shape) != 2 or self.amplitude.shape[0] != self.amplitude.shape[1]:
                raise ValueError, "Pupil amplitude image must be 2-D and square"

Apparently 2to3 does not fix it, and a manual conversion to brakets is necessary.

**Comment by mperrin** [comment]
Hi Mario, 

Thanks - so far as I know you may be the first person to try this on Python 3! Please do keep letting us know what you encounter. 

If you can make fixes in your local copy so that it works on Python 3, by all means we'd be happy to include those (either via github pull request or if you would rather just email them to me).

**Comment by josePhoenix** [comment]
@marioavellaneda - When you encounter an issue, can you include the exception and trace back (even if it's just a SyntaxError)? Thanks!

**Comment by josePhoenix** [comment]
See #86 for progress on this issue. If you'd like to try it out with Python 3, make a new virtualenv and install with `pip` as follows:

`pip install -e git+https://github.com/josePhoenix/poppy.git@remove_helpers#egg=poppy`

(n.b. This version is missing some packaging helpers from the upstream package template we were using that did not make the transition to Python 3 for some reason. They shouldn't impede your use of the package.)

To run the test suite, you must additionally `pip install pytest`. Then change directories to where pip cloned the POPPY source, and run `python setup.py test`.

**Comment by josePhoenix** [comment]
This is now merged in to master, and our next release will be compatible with Python 3.4 as well as 2.7.
