### ISSUE TITLE
Test needed: Exercise poppy.Instrument._getWeights under different circumstances

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#76]
We should at minimum verify that it works without pysynphot installed, and that when pysynphot is not installed it won't accept WAVEUNIT != 'Angstrom'.

See the silly error fixed in https://github.com/mperrin/poppy/pull/75 for example. That should have been caught by the test suite.

**Comment by mperrin** [comment]
@josePhoenix do you think you are likely to work on this in the next month? If not let's delay it to the next milestone 0.5.1. Whichever you prefer is fine with me.

**Comment by josePhoenix** [comment]
Yes, I should be able to do this before the June AAS.

**Comment by mperrin** [comment]
Stale issue. No particular action needed at this time.
