### ISSUE TITLE
Investigate whether pyFFTW wisdom saving/loading is working as specified

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#85]
I noticed in some logging output from Charles Lajoie that it was hitting the "Evaluating PyFFT optimal algorithm for ..." step even though he'd transformed 4k by 4k complex arrays many times before. I told him to turn off FFTW, with dropped the calculation time by 10 sec, but we should make sure that it's actually using the wisdom values. If it is, we should change the logging output to reflect that.

**Comment by mperrin** [comment]
I had intermittent problems with this in the past too. Not sure why under some circumstances it does or does not save.

**Comment by mperrin** [comment]
I wonder if #122 might also have fixed this old issue.

**Comment by mperrin** [comment]
I think you added a test case for this, so this is probably safe to close now?

**Comment by mperrin** [comment]
I just tested the test case, and I also tested the behavior directly (e.g. does `import poppy` result in the FFTW wisdom being loaded successfully.) All seems to be working ok.
