### ISSUE TITLE
Implement Fresnel Propagation

### ISSUE THREAD

**Issue by douglase** [mperrin/poppy#95]
I've made a first attempt at extending POPPY to support Fresnel propagation in a branch in my fork: 

https://github.com/douglase/poppy/tree/fresnel

The new module inherits the Wavefront class and added the necessary functions, methods and properties for Fresnel diffraction calculations. I chose a separate submodule because don't want to break any existing POPPY routines. 

This new class has passed my initial tests. Demos of a telescope, diffraction from a circular aperture and the necessary Gaussian waist calculations are in this notebook: http://nbviewer.ipython.org/gist/douglase/600d6e4d88336f4ed0c4 (I left debug enabled, so there's lots of details in the notebook).

Some future work:
* Formal testing
* Make docstrings Astropy Guideline complaint 
* Streamlined logging

Is this a feature others would find useful? 

I'm going to keep working and testing this, but I wanted to open it up for outside input while things are still fresh.

**Comment by mperrin** [comment]
Whoa. You have just totally made my day.  Yes this is absolutely a feature others will find useful! And it was on my own road map to figure out some time to implement in the next year or two.  Man this is fantastic. I promise to take a careful and close read through of this later, but am traveling for the next two weeks so will not be able to look at it in detail until likely June.   But this looks great just from skimming the notebook.

**Comment by josePhoenix** [comment]
Very, very cool! :+1: 

I was looking through the code and thought I should mention some of the naming conventions used semi-consistently in POPPY (for ease of eventual integration with the main branch): class names are `CapitalizedLikeThis`, except for classes where the words are capitalized acronyms (e.g. `FQPM_FFT_Aligner`), and method names are `camelCase`.

(Blair Porterfield says hi, by the way!)

**Comment by mperrin** [comment]
We should at some point think about cleaning up the main codebase to be more pep8 compliant. That's a relatively low priority overall and I admit I did not think much about it when I started writing all this in 2010 so there are parts that are messier than I would write today. Hard to be sure whether improving this is worth breaking back-compatibility; at some point we could add pep8 compliant names as synonyms and have a transitional period where both work.

**Comment by douglase** [comment]
@mperrin I'm a little confused, do you feel extensions should be pep8, or follow the existing convention? 
I'm all over the map and still need to better absorb pep8.  

@josePhoenix say hello to Blair!

**Comment by josePhoenix** [comment]
I think @mperrin means that PEP8 compliance in the main POPPY codebase is more of an aspiration than a policy at this point. It would be nice if new extensions followed PEP8, just because they won't have to be renamed later when we make a push for codebase-wide PEP8 naming conventions.

**Comment by douglase** [comment]
@josePhoenix ok, makes sense, when I get a chance I'll go over PEP8 and the astropy coding guidelines and try to bring things in line.

**Comment by mperrin** [comment]
"more of an aspiration than a policy at this point" -- yep, that's pretty much it!

**Comment by josePhoenix** [comment]
@douglase I'd be happy to help get this ready for inclusion if you could open a PR :)

**Comment by douglase** [comment]
Thanks for the reminder. I fixed a few things (details below) and created a pull request, but there is still work to do obviously.

I just went through and got the method and class names closer to PEP8, also @kuravih had found that things broke if you didn't have FFTW/pyfftw installed so I just fixed that as well. 

I've also added some rudimentary tests but more rigorous testing is in the works.

**Comment by mperrin** [comment]
Now that there is a `fresnel` branch in this repository, merging @douglase's code, what's next? 

Some loose brainstorming: 

- [ ] double check for consistency with latest updates to poppy/master (@josephoenix)
- [ ] docstring review and consistent-ification (@mperrin)
- [ ] rename fresnel.Wavefront to FresnelWavefront to minimize ambiguity?
- [ ] evaluate public API of fresnel.Wavefront. Should any of these functions become marked with underscores for implementation-internal/private or do we let it all be the public API? I would like to suggest some minor renamings like `ptp` -> `_propagate_ptp` and similar, for more consistent labeling with respect to `poppy_core.Wavefront._propagateMFT` and the like. 
- [ ] additional test cases (all?)

**Comment by mperrin** [comment]
question to @douglase : in the `fresnel.Wavefront.fft_coords` function the docstring says 'replaces poppy.wavefront.coordinates()'.  Is there a reason you didn't just name that function `coordinates` to subclass and replace the parent class' function?

**Comment by douglase** [comment]
Only that I wasn't sure there weren't cases where the original coordinates function wouldn't be useful.

**Comment by douglase** [comment]
W.r.t task list:

I agree _propagate_ptp etc... Would make sense. 

Tests: @kuravih and I are working on replicating the PROPER test coronagraph and I would like to add that as a test once we have validated it, since the current tests don't test many of the core functions. A version of the Hubble example would also be good, since that does not require new optics.

Adding a way to handle image planes gracefully  is also important.

**Comment by mperrin** [comment]
I started working on improving the Hubble example into a test case this morning, adding in the offset primary support pads to better match PROPER's HST model (and the real thing :-). 

Sounds like we could plan to split the effort and you concentrate on the PROPER Lyot case and I'll work on the HST one?

Agreed re image planes.

**Comment by douglase** [comment]
This division of tests work sounds good.

**Comment by mperrin** [comment]
More work in progress - see latest comment on #103

**Comment by mperrin** [comment]
Fresnel merged to master. Many thanks and much credit to @douglase for getting this all started and contributing all this code.

**Comment by douglase** [comment]
And thanks to @mperrin and @josePhoenix for their efforts and patience to make the code readable and robust.
