### ISSUE TITLE
BandLimitedCoron contains JWST-specific details

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/poppy#98]
There are code paths in the BandLimitedCoron optical element that are specific to simulating NIRCam. If feasible, these should be factored out into classes in WebbPSF.

**Comment by mperrin** [comment]
I agree, this should be moved to WebbPSF.

**Comment by mperrin** [comment]
Shall we try to do this for 0.4, or punt until later? 

I would say we should move these classes to webbpsf, and mark the existing classes in poppy as Deprecated but not delete them in 0.4, then they could be deleted in some future 0.5.

**Comment by josePhoenix** [comment]
You would know better than I whether there's broader uses for the BandLimitedCoron as currently implemented... if not, I agree that "moving" the class to WebbPSF (deprecating, copying, deleting in 0.5) is the best move.

**Comment by mperrin** [comment]
Hmm, looking at the code now the `circular` and `linear` BLCs are generic and not NIRCam-specific. Those should be left in `poppy`.  I'll take a shot at moving the NIRCam-specific stuff to a subclass in `webbpsf`, and leaving the rest behind.

**Comment by mperrin** [comment]
Huh, I hadn't realized that `DeprecationWarnings` are silently hidden by default. I've added a warning, but it's not going to have much effect. Still, I suspect the number of function calls to that function globally that are not our own code in `webbpsf` is vanishingly small, so I am not too concerned here.
